# Generated by Django 5.0.6 on 2024-07-19 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='ruta',
            field=models.TextField(default='None'),
        ),
        migrations.AddField(
            model_name='producto',
            name='ruta',
            field=models.TextField(default='None'),
        ),
    ]
