# Generated by Django 5.0.6 on 2024-07-19 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_categoria_ruta_producto_ruta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='ruta',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='ruta',
        ),
    ]
