# Generated by Django 5.0.6 on 2024-07-19 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_usuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
